version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
      - $(aws ecr get-login  --no-include-email --region us-east-2)
  build:
    commands:
      - echo "Entered build phase"
      - cd AuditChecklist
      - mvn compile
      - mvn package
      - echo " building docker image"
      - docker build -t service/checklist .
      - docker tag service/checklist 885843804602.dkr.ecr.us-east-2.amazonaws.com/pod2-ij50-checklist-repo:checklist
  post_build:
    commands:
    - echo "Entered the post-build phase"
    - docker push 885843804602.dkr.ecr.us-east-2.amazonaws.com/pod2-ij50-checklist-repo:checklist
    - printf '[{"name":"checklist-container","imageUri":"%s"}]' 885843804602.dkr.ecr.us-east-2.amazonaws.com/pod2-ij50-checklist-repo:checklist > taskdefinition.json
artifacts:
  files:
    - AuditChecklist/taskdefinition.json
    