version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
      - $(aws ecr get-login  --no-include-email --region us-east-2)
  build:
    commands:
      - echo "Entered build phase"
      - cd AuditSeverity
      - mvn compile
      - mvn package
      - echo " building docker image"
      - docker build -t service/severity .
      - docker tag service/severity 885843804602.dkr.ecr.us-east-2.amazonaws.com/pod2-ij50-severity-repo:severity
  post_build:
    commands:
    - echo "Entered the post-build phase"
    - docker push 885843804602.dkr.ecr.us-east-2.amazonaws.com/pod2-ij50-severity-repo:severity
    - printf '[{"name":"severity-container","imageUri":"%s"}]' 885843804602.dkr.ecr.us-east-2.amazonaws.com/pod2-ij50-severity-repo:severity > taskdefinition.json
artifacts:
  files: 
    - AuditSeverity/taskdefinition.json
    