version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
      - $(aws ecr get-login  --no-include-email --region us-east-2)
  build:
    commands:
      - echo "Entered build phase"
      - cd authorization
      - mvn compile
      - mvn package
      - echo " building docker image"
      - docker build -t service/authapp .
      - docker tag service/authapp 885843804602.dkr.ecr.us-east-2.amazonaws.com/pod2-ij50-repo:authapp
  post_build:
    commands:
    - echo "Entered the post-build phase"
    - docker push 885843804602.dkr.ecr.us-east-2.amazonaws.com/pod2-ij50-repo:authapp
    - printf '[{"name":"authapp-container","imageUri":"%s"}]' 885843804602.dkr.ecr.us-east-2.amazonaws.com/pod2-ij50-repo:authapp > taskdefinition.json
artifacts:
  files: 
    - authorization/taskdefinition.json
    